### ISSUE TITLE
Error org.freedesktop.DBus.Error.UnknownMethod: No such method “ShowNotifications”

### ISSUE THREAD

**Issue by akhiljalagam** [sencer/i3-notifier#1]

**Comment by sencer** [comment]
Try stopping the other notification manager first, then restart this.

**Comment by AkhilJalagam** [comment]
No use.
I am using ubuntu gnome 20.04 with i3wm and dunst.


![image](https://user-images.githubusercontent.com/21128035/89014852-c29bba80-d333-11ea-88cb-d754a6450cad.png)

**Comment by sencer** [comment]
Well according to your screenshot you killed dunst but didn't restart i3-notifier. So it is not "no use." I am not going to use "Issues" to provide tutorial on basics.

**Comment by nicklan** [comment]
I'm having this issue too. I've done `killall dunst`, and then tried to restart i3-notifier with `dbus-send --session --print-reply --dest=org.freedesktop.Notifications /org/freedesktop/Notifications org.freedesktop.Notifications.ShowNotifications`, but I still get the "No such method" error.

Perhaps there's some basic thing I missing, but I don't see anything in the docs about how to restart i3-notifier other than running that dbus-send command.

If I am missing something basic, and you don't want to use issues to address basics, maybe put the basics in the README?

**Comment by sencer** [comment]
Why do you think `dbus-send --session --print-reply --dest=org.freedesktop.Notifications /org/freedesktop/Notifications --dest=org.freedesktop.Notifications /org/freedesktop/Notifications org.freedesktop.Notifications.ShowNotifications` will restart `i3-notifier`. It merely tells the running `i3-notifier` process to show the notifications. To restart it you will need to kill it & restart the way you started initially; that is calling `i3-notifier` command. Now if you think I should put readme this information I would happily merge a decent pull request.

To start `i3-notifier` please bring up a terminal, write `i3-notifier` and press enter. To kill it run `pkill i3-notifier`. To restart it, first kill it and then restart it.

**Comment by nicklan** [comment]
Ahh I see, thanks. 

Yeah, it's not clear that you need to start it manually, and when installed via pip (as recommended in the readme) it's not in your path (unless you've added `~/.local/bin` to your path which isn't the default). I actually did want to try running it as a command but didn't realize that's where it had ended up as I basically never use pip otherwise.

**Comment by sencer** [comment]
Thanks for the feedback. Updated the README.
